In [2]:
import pytest
from src.baseSIR import mle
from src.baseSIR import mle_sir
import numpy as np

In [6]:
beta = 3
gamma = 1
mu = 0
X0 = [2,1,0]
rng = np.random.default_rng(1912)
tmax = 10
t_step = 0.1
tested,times_test, timed_test = mle_sir(X0,mu,beta,gamma,tmax,t_step,rng)
print(timed_test)
print(times_test)

[[2 1 0]
 [1 2 0]
 [0 3 0]
 [0 2 1]
 [0 1 2]
 [0 0 3]]
[0.         0.7983963  1.05073965 1.39331947 1.4533709  2.3108022 ]


In [9]:
print(mle(beta,gamma,timed_test,times_test,10))

-2.231782093362974


In [12]:
val_1 = np.log(3/3 * 1 * 2 * np.exp(-(3/3 *1 *2 +1)*(0.7983963)))
val_2 = np.log(3/3 * 2 * 1 * np.exp(-(3/3 *2 *1 +2)*(1.05073965 - 0.7983963)))
val_3 = np.log(1 * 3 * np.exp(-(3/3 *0 *3 + 3)*(1.39331947 - 1.05073965)))
val_4 = np.log(1 * 2 * np.exp(-(3/3 *0 *2 +2)*(1.4533709- 1.39331947)))
val_5 = np.log(1 * 1 * np.exp(-(3/3 *0 *1 + 1)*(2.3108022 - 1.4533709)))
True_val = val_1 + val_2 + val_3 + val_4 + val_5
print(True_val)

-2.2317820896520546
