In [1]:
import time
import numpy as np
import pymc as pm
from src.baseSIR import timed_sir
from src.baseSIR import real_sir
import arviz as az
from decimal import Decimal, ROUND_UP


#Initialise RNG

# Run the "real world"
X0 = [999, 1, 0]
beta = 3
gamma = 1
mu = 0
test_time = 100
tstep = Decimal(0.05)
start_time = time.time()
times = []
for i in range(10):
    rng = np.random.default_rng(i)
    final_time =  tstep * (Decimal(timed_sir(X0, mu, beta, gamma, test_time, rng) )/ tstep).quantize(1,rounding=ROUND_UP)
    times.append(final_time)
    if i % 10 == 0:
        print(".",end="")
print('\n')
print(f"Time run took {time.time() - start_time} seconds to run!")
print(f"Optimal tmax = {np.max(times)}")

WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


.

Time run took 0.4165918827056885 seconds to run!
Optimal tmax = 15.60000000000000086597395921


In [2]:
from src.baseSIR import no_ext_sir
X0 = [999, 1, 0]
gamma = 1
beta = 3
mu = 0
tmax = 15.60
tstep = 0.05

rng = np.random.default_rng(1)
start_time = time.time()
reality = no_ext_sir(X0, mu, beta, gamma, tmax, tstep, rng)
print(f"Reality took {time.time() - start_time} seconds to run!")
def ints(x):
    return int(x)
ints_v = np.vectorize(ints)

Reality took 0.04666709899902344 seconds to run!


In [3]:
reality_100 = reality / 10
reality_100[:, 0] = ints_v(np.floor(reality_100[:, 0]))
reality_100[:, 1] = ints_v(np.ceil(reality_100[:, 1]))
reality_100[:, 2] = ints_v(100 - reality_100[:, 1] - reality_100[:, 0])

reality_10 = reality / 100
reality_10[:, 0] = np.floor(reality_10[:, 0])
reality_10[:, 0] = reality_10[:, 0].astype(int)
reality_10[:, 1] = np.ceil(reality_10[:, 1])
reality_10[:, 1] = reality_10[:, 1].astype(int)
reality_10[:, 2] = 10 - reality_10[:, 1] - reality_10[:, 0]
reality_10[:, 2] = reality_10[:, 2].astype(int)

In [4]:
print(reality_100[0][0])

99.0


In [5]:
print(reality)

[[999   1   0]
 [998   2   0]
 [997   3   0]
 [997   3   0]
 [997   3   0]
 [997   3   0]
 [997   3   0]
 [996   4   0]
 [995   5   0]
 [992   7   1]
 [991   8   1]
 [991   8   1]
 [990   8   2]
 [990   8   2]
 [988   8   4]
 [988   8   4]
 [986   9   5]
 [985   9   6]
 [984   8   8]
 [983   7  10]
 [982   7  11]
 [982   7  11]
 [979  10  11]
 [978  10  12]
 [977  11  12]
 [975  11  14]
 [973  13  14]
 [972  14  14]
 [970  16  14]
 [964  22  14]
 [962  24  14]
 [958  28  14]
 [953  33  14]
 [950  34  16]
 [947  37  16]
 [940  43  17]
 [934  48  18]
 [929  48  23]
 [924  53  23]
 [917  57  26]
 [906  66  28]
 [895  74  31]
 [885  82  33]
 [870  91  39]
 [860  98  42]
 [845 110  45]
 [829 125  46]
 [818 126  56]
 [799 136  65]
 [781 146  73]
 [758 162  80]
 [749 162  89]
 [730 170 100]
 [717 172 111]
 [707 173 120]
 [680 191 129]
 [659 208 133]
 [640 223 137]
 [620 233 147]
 [608 235 157]
 [583 246 171]
 [562 255 183]
 [539 266 195]
 [512 277 211]
 [490 290 220]
 [465 305 230]
 [445 312 

In [6]:
X0 = [999, 1, 0]
rng = np.random.default_rng(10)
gamma = 1
beta = 3
mu = 0
tstep = 0.05
test_time = 100
tmax = float(Decimal(tstep) * (Decimal(timed_sir(X0, mu, beta, gamma, test_time, rng) )/ Decimal(tstep)).quantize(1,rounding=ROUND_UP))
rng = np.random.default_rng(10)
t = timed_sir(X0, mu, beta, gamma, test_time, rng)
print(t)
print(tmax)
start_time = time.time()
lens = 0
rng = np.random.default_rng(10)
for i in range(100):
    reality = no_ext_sir(X0, mu, beta, gamma, tmax, tstep, rng)
#print(reality)
    lens += len(reality)
print(tmax)
print(tstep)
print(tmax/tstep)
print(lens/100)

9.067955309298277
9.1
9.1
0.05
181.99999999999997
182.0
