In [6]:
import time
import numpy as np
import pymc as pm
from src.baseSIR import no_ext_sir
from src.baseSIR import real_sir
import arviz as az



#Initialise RNG
seed = 1
rng = np.random.default_rng(seed)
def sim_sir(model_rng, b, g, size=None):
    return no_ext_sir(X0, mu, b, g, tmax, tstep, rng) * factor


# Run the "real world"
X0 = [900, 100, 0]
beta = 3
gamma = 1
mu = 0
tmax = 10
tstep = 0.05
start_time = time.time()
reality = no_ext_sir(X0, mu, beta, gamma, tmax, tstep,rng)
#rng = np.random.default_rng(seed)
#test_reality = real_sir(X0, mu, beta, gamma, tmax, tstep,rng)
#print(f"The New function gives a {test_reality == reality} result!")
print(f"Reality took {time.time() - start_time} seconds to run!")

Reality took 0.027016639709472656 seconds to run!


In [11]:
print(reality)

[[900 100   0]
 [885 106   9]
 [872 112  16]
 [854 128  18]
 [840 139  21]
 [826 145  29]
 [801 164  35]
 [776 184  40]
 [756 198  46]
 [730 219  51]
 [709 223  68]
 [680 240  80]
 [656 253  91]
 [636 256 108]
 [622 253 125]
 [595 268 137]
 [570 285 145]
 [547 301 152]
 [526 308 166]
 [505 313 182]
 [485 321 194]
 [456 333 211]
 [428 342 230]
 [408 349 243]
 [384 360 256]
 [365 364 271]
 [345 373 282]
 [317 380 303]
 [296 380 324]
 [276 381 343]
 [256 381 363]
 [234 388 378]
 [221 378 401]
 [210 371 419]
 [197 366 437]
 [183 366 451]
 [174 357 469]
 [167 345 488]
 [154 338 508]
 [149 329 522]
 [138 323 539]
 [132 313 555]
 [127 305 568]
 [123 300 577]
 [116 291 593]
 [107 287 606]
 [102 281 617]
 [ 97 270 633]
 [ 93 266 641]
 [ 87 264 649]
 [ 81 257 662]
 [ 79 248 673]
 [ 77 238 685]
 [ 74 233 693]
 [ 71 228 701]
 [ 69 216 715]
 [ 64 203 733]
 [ 62 192 746]
 [ 57 191 752]
 [ 56 179 765]
 [ 55 170 775]
 [ 53 162 785]
 [ 52 155 793]
 [ 51 147 802]
 [ 50 142 808]
 [ 49 137 814]
 [ 49 129 

In [7]:
# Resolution X100
X0 = [9, 1, 0]
mu = 0
tmax = 10
tstep = 0.05
factor = 100
start_time = time.time()
with pm.Model() as test:
    b = pm.HalfNormal("b", 5)
    g = pm.HalfNormal("g", 5)
    s = pm.Simulator("s", sim_sir, params=(b, g), epsilon=500, observed=reality)
    idata3 = pm.sample_smc(progressbar=False)
print(f"Resolution X3 took {time.time() - start_time} seconds to fit!")

Initializing SMC sampler...
Sampling 6 chains in 6 jobs


Resolution X3 took 303.45154428482056 seconds to fit!


C:\Users\ollie\anaconda3\envs\PLS Research\lib\site-packages\arviz\data\base.py:221: UserWarning: More chains (6) than draws (5). Passed array should have shape (chains, draws, *shape)
  warnings.warn(


In [8]:
idata3.sample_stats

<xarray.Dataset>
Dimensions:                  (chain: 6, draw: 5)
Coordinates:
  * chain                    (chain) int32 0 1 2 3 4 5
  * draw                     (draw) int32 0 1 2 3 4
Data variables:
    log_marginal_likelihood  (chain, draw) object nan nan nan ... nan nan -9.508
    beta                     (chain, draw) object 0.00621795654296875 ... 1
    accept_rate              (chain, draw) object 0.6218 0.4882 ... 0.04739
Attributes:
    created_at:                 2023-11-07T10:59:11.969301
    arviz_version:              0.16.0
    inference_library:          pymc
    inference_library_version:  5.6.1
    _n_draws:                   2000
    threshold:                  0.5
    _n_tune:                    9
    correlation_threshold:      0.01
    _t_sampling:                303.2604818344116

In [9]:
x = idata3.posterior.b
x = np.array(x)
print(az.kde(np.ndarray.flatten(x))[0][np.argmax(az.kde(np.ndarray.flatten(x))[1])])

2.9409235066878585


In [10]:
y = idata3.posterior.g
y = np.array(y)
print(az.kde(np.ndarray.flatten(y))[0][np.argmax(az.kde(np.ndarray.flatten(y))[1])])

0.8976316569723574
